apiVersion: v1
kind: Pod
metadata:
  name: centos-cli
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello $(date); sleep 10;done"]