apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  labels:
    app: echoserver-service
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: echoserver